### ISSUE TITLE
The filtering for the graph is not working.

### ISSUE THREAD

**Issue by jonahschueller** [Process-Discover-Log-Skeleton/Log-Skeleton-Frontend#24]
**Describe the bug**
The graph should present a minimal version of the graph. Meaning the transitive relationships should only show the necessary edges and the others are implicit. 

Example: Let's assume the relationship contains the items: `{(a, b), (b, c), (a, c)}`. The graph should only the items `(a, b)` and `(b, c)` since the item `(a, c)` is implied by the path from `a` over `b` over `c`.

The current implementation does not calculate the correct thing.

**Algorithm**
The algorithm should do the following:

Let `G = {N, E}` the set of nodes and edges.

- For each node `n` in `N`:
   - Calculate all the nodes `R(n)` that can be reached starting from `n`
   - For each outgoing edge `e` from `n` called `E(n)`
       - Check if `R(n) = R'(n)`, where `R'(n)` is the set of reachable nodes in the graph `G' = {N, E \ e}`

**Comment by mnghiap** [comment]
I fixed and renamed the function to minimalTransitive to avoid confusion. Tested the function on some small graphs and it works well. Correctness for "larger" graphs is not yet guaranteed. Created a PR so it can go to development for further testing.
